### ISSUE TITLE
This api 'curl -X GET %url/role-strategy/strategy/getAllRoles  --data "type=projectRoles" '  Work is not correct？

### ISSUE THREAD

**Issue by peterpijing** [LegallGuillaume/jenkins-role-strategy-api-python#3]

**Comment by LegallGuillaume** [comment]
hi, 

try:
curl -X %url/role-strategy/strategy/getAllRoles

no possibility at the moment to choose the projectRoles or the items

**Comment by peterpijing** [comment]
HI,What do you mean this api do not support the specified projectRoles,Only support the globalRoles?

**Comment by LegallGuillaume** [comment]
Yes, because strategy plugin not support projectRoles rest api.

On strategy plugin there are no REST API at the moment (soon)

**Comment by peterpijing** [comment]
Can you provide a python api for how to list all role? and each corresponding pattern?
That is the corresponding relationship in Project roles ,role and pattern?

**Comment by LegallGuillaume** [comment]
For the moment I work on project very important but when I could I do it

**Comment by peterpijing** [comment]
Thanks,I also find your's comment  ：
（Can't work now？）
I have modify doGetAllRoles to chose type :curl -X localhost:8080/role-strategy/strategy/getAllRoles --data "type=globalRoles"type : globalRoles, projectRoles, slaveRoles 
I have modify doAssignRole to allow list of sid :curl -X POST localhost:8080/role-strategy/strategy/assignRole --data "type=globalRoles&roleName=ADM&sid=username1,username2,group1"One query to assign many sid (users, groups)
I have modify doUnassignRole to allow list of sid :curl -X POST localhost:8080/role-strategy/strategy/unassignRole --data "type=globalRoles&roleName=ADM&sid=username1,username2,group1"One query to assign many sid (users, groups)


--

**Comment by LegallGuillaume** [comment]
Extract from https://wiki.jenkins.io/display/JENKINS/Role+Strategy+Plugin
Unassign role: curl -X POST localhost:8080/role-strategy/strategy/unassignRole --data "type=globalRoles&roleName=AMD&sid=username"

List roles: curl -X GET localhost:8080/role-strategy/strategy/getAllRoles

For the "One query to assign many sid", it is a subject of pull request

**Comment by peterpijing** [comment]
your python api have a bug in login?
        if not self.is_connected():
            raise PyjarsException('Authentification Failed', 401,
                                  dict(
                                      login=login,
                                      password='****',
                                      url=url,
                                      ssl=self.ssl_verify,   --->AttributeError: 'RoleStrategy' object has no attribute 'ssl_verify'
                                      cert=ssl_cert))
